@DotNet8WebApi.CustomFixedWindowRateLimiterIntegration_HostAddress = http://localhost:5093

GET {{DotNet8WebApi.CustomFixedWindowRateLimiterIntegration_HostAddress}}/weatherforecast/
Accept: application/json

###
